# Generated by Django 3.2.8 on 2022-08-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablecolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumns',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablerecords'),
        ),
    ]
