# Generated by Django 3.2.8 on 2022-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tablecolumns_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumns',
            name='column_type',
            field=models.CharField(max_length=20, verbose_name=[('String', 'String'), ('Boolean', 'Boolean'), ('Number', 'Number'), ('Email', 'Email'), ('DateTime', 'DateTime')]),
        ),
    ]
