# Generated by Django 3.2.8 on 2022-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tablecolumns_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerecords',
            name='columns',
            field=models.IntegerField(null=True),
        ),
    ]
